### ISSUE TITLE
Pash fails on ./evaluation/intro/hello-world.sh

### ISSUE THREAD

**Issue by dkarnikis** [andromeda/pash#215]
commit id: 7f26571981073c67fe75c9fc3e86f741195ba27f
Pash output (3712) is the same with the bash execution

```
Traceback (most recent call last):
  File "/root/pash/pash/compiler/pash_runtime.py", line 729, in <module>
    main()
  File "/root/pash/pash/compiler/pash_runtime.py", line 46, in main
    compile_optimize_script(args.input_ir, args.compiled_script_file, args)
  File "/root/pash/pash/compiler/pash_runtime.py", line 81, in compile_optimize_script
    asts_and_irs = compile_candidate_df_region(candidate_df_region, config.config)
  File "/root/pash/pash/compiler/pash_runtime.py", line 145, in compile_candidate_df_region
    compiled_asts = compile_asts(candidate_df_region, fileIdGen, config)
  File "/root/pash/pash/compiler/ast_to_ir.py", line 111, in compile_asts
    expanded_ast = expand_command(ast_object, config)
  File "/root/pash/pash/compiler/expand.py", line 405, in expand_command
    return ast_to_ir.ast_match(command, expand_cases, config)
  File "/root/pash/pash/compiler/ast_to_ir.py", line 898, in ast_match
    return cases[ast_node.construct.value](*args)(ast_node)
  File "/root/pash/pash/compiler/expand.py", line 376, in <lambda>
    lambda ast_node: expand_simple(ast_node, config)),
  File "/root/pash/pash/compiler/expand.py", line 438, in expand_simple
    node.arguments = expand_args(node.arguments, config)
  File "/root/pash/pash/compiler/expand.py", line 234, in expand_args
    new = expand_arg(arg, config, quoted = quoted)
  File "/root/pash/pash/compiler/expand.py", line 279, in expand_arg
    new = expand_arg_char(arg_char, quoted, config)
  File "/root/pash/pash/compiler/expand.py", line 321, in expand_arg_char
    raise Unimplemented("command substitution", arg_char)
expand.Unimplemented: ('command substitution', ['B', ['Command', [1, [], [[['C', 117], ['C', 110], ['C', 97], ['C', 109], ['C', 101]]], []]]])
3712
```

**Comment by angelhof** [comment]
I fixed the output printing. For reference, this is not a failure, but rather the runtime compiler not parallelizing a script, which means that the original one is run.
